# import:
  #- ~/.config/alacritty/themes/argonaut.yml

font:
  size: 10.0
  normal:
    family:
      JetBrains Mono 

cursor:
  style:
    blinking: On

window:
  dynamic_title: true
  title: alacritty
  #  decorations: none
  opacity: 0.7
  startup_mode: Maximized
  padding:
    x: 25
    y: 0
