import:
  - ~/.config/alacritty/themes/hyper.yml

font:
  size: 7.0
  normal:
    family:
      JetBrainsMono Nerd Font 

cursor:
  style:
    blinking: On

window:
  dynamic_title: true
  title: alacritty
  #  decorations: none
  opacity: 0.7
  startup_mode: Maximized
  padding:
    x: 25
    y: 0
