import = ["/home/gekevin/.config/alacritty/themes/tokyo-night.toml"]

[cursor.style]
blinking = "On"

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"

[window]
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
title = "alacritty"

[window.padding]
x = 25
y = 0
