#!/bin/bash

CONFIG=$HOME/.config
PRIMARY_MONITOR=eDP
PRIMARY_MONITOR_MODE=2256x1504
EXTERNAL_MONITOR=DisplayPort-2
EXTERNAL_MONITOR_MODE=2256x1504


# UI
pgrep -x sxhkd > /dev/null || sxhkd &
set-bg &
$CONFIG/polybar/launch.bash $CONFIG/polybar/minimal/dark.ini $EXTERNAL_MONITOR &
picom &
dunst &

# Registry xsecurelock as xss locker.
xss-lock xsecurelock &

# borders
bspc config border_width 0
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config focused_border_color "$color1"
bspc config normal_border_color "$color15"

# bspwm config
bspc config window_gap          15
bspc config split_ratio          0.52

bspc config focus_follows_pointer false

# monocle
bspc config gapless_monocle      false
bspc config borderless_monocle   false

# force apps to open in specific workspaces
bspc rule -a discord desktop=9 state=tiled

# start up apps
alacritty &
browser &

if [[ $(xrandr -q | grep "$EXTERNAL_MONITOR connected") ]]; then
    xrandr \
        --output $EXTERNAL_MONITOR --primary --mode $EXTERNAL_MONITOR_MODE --rotate normal --left-of $PRIMARY_MONITOR \
        --output $PRIMARY_MONITOR --mode $PRIMARY_MONITOR_MODE --rotate normal

    # switch order of monitors
    bspc wm -O $EXTERNAL_MONITOR $PRIMARY_MONITOR

    bspc monitor $EXTERNAL_MONITOR -d 1 2 3 4 5 6 7 8
    bspc monitor $PRIMARY_MONITOR -d 9
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# laptop touchpad
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1
xsetroot -cursor_name left_ptr

# disable tap to click
synclient MaxTapTime=0
synclient VertScrollDelta=-111

# xinput settings (run xinput list, xinput list-props <ID>)
# AMD F13 laptop settings:
# Enable natural scrolling
xinput --set-prop 11 305 1
# Enable tap clicking
xinput --set-prop 11 326 1
