#!/bin/bash

# UI
pgrep -x sxhkd > /dev/null || sxhkd &
set-bg &
~/.config/polybar/launch.sh --forest &
picom &
dunst &

# source colors from pywal
# . "${HOME}/.cache/wal/colors.sh"

# Registry xsecurelock as xss locker.
xss-lock xsecurelock &

# borders
bspc config border_width 0
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config focused_border_color "$color1"
bspc config normal_border_color "$color15"

# bspwm config
bspc config window_gap          15
bspc config split_ratio          0.52

bspc config focus_follows_pointer false

# monocle
bspc config gapless_monocle      false
bspc config borderless_monocle   false

bspc rule -a firefox rectangle 1920x1080+0+0 center=true

# force apps to open in specific workspaces
bspc rule -a discord desktop=9 state=tiled
bspc rule -a teams-for-linux desktop=9 state=tiled

# start up apps
alacritty &
browser &

# set monitors
EXTERNAL=HDMI1
EXTERNAL_MODE=1920x1080
PRIMARY=eDP1

if [[ $(xrandr -q | grep "$EXTERNAL connected") ]]; then
    xrandr \
        --output $EXTERNAL --primary --mode $EXTERNAL_MODE --rotate normal --left-of $PRIMARY \
        --output $PRIMARY --mode 1920x1080 --rotate normal
        #--output VIRTUAL1 --mode 2800x1752_60.00  --left-of HDMI1
    # switch order of monitors
    bspc wm -O $EXTERNAL $PRIMARY

    bspc monitor $EXTERNAL -d 1 2 3 4 5 6 7 8
    bspc monitor $PRIMARY -d 9
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# laptop touchpad
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1
xsetroot -cursor_name left_ptr

# disable tap to click
synclient MaxTapTime=0
synclient VertScrollDelta=-111

# xinput settings (run xinput list, xinput list-props <ID>)
# AMD F13 laptop settings:
# Enable natural scrolling
xinput --set-prop 11 305 1
# Enable tap clicking
xinput --set-prop 11 326 1
