#!/bin/bash

# UI
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/material/scripts/pywal.sh ~/dotfiles/wallpapers/unsplash/elliot-engelmann-dark-mountain.jpg &
 ~/.config/polybar/launch.sh --forest &
picom &
dunst &

# source colors from pywal
. "${HOME}/.cache/wal/colors.sh"

# borders
bpsc config border_width 3
bspc config top_padding 0
bspc config bottom_padding 0
bspc config focused_border_color "$color15"
bspc config normal_border_color "$color1"

# bspwm config
bspc config window_gap          15
bspc config split_ratio          0.52

bspc config focus_follows_pointer false

# monocle
bspc config gapless_monocle      false
bspc config borderless_monocle   false

bspc rule -a firefox rectangle 1920x1080+0+0 center=true

# force apps to open in specific workspaces
bspc rule -a discord desktop=9 state=tiled

# start up apps
alacritty &
google-chrome-stable &

# set monitors
EXTERNAL=HDMI-1
PRIMARY=eDP-1

if [[ $(xrandr -q | grep "$EXTERNAL connected") ]]; then
    xrandr \
        --output $EXTERNAL --primary --mode 1920x1080 --rotate normal --right-of $PRIMARY \
        --output $PRIMARY --mode 1920x1080 --rotate normal
    # switch order of monitors
    bspc wm -O $EXTERNAL $PRIMARY

    bspc monitor $EXTERNAL -d 1 2 3 4 5 6 7 8
    bspc monitor $PRIMARY -d 9
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# laptop touchpad
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1
xsetroot -cursor_name left_ptr

# disable tap to click
synclient MaxTapTime=0
synclient VertScrollDelta=-111

# scrolling idk
xinput --set-prop 15 303 1
